from __future__ import annotations

from typing import Protocol


class ViteFactoryContract(Protocol):
    def tags(self, entries, build_directory: str | None = None): ...

    def asset(self, entry: str, build_directory: str | None = None): ...

    def content(self, asset: str, build_directory: str | None = None): ...

    def use_hot_file(self, path): ...

    def use_build_directory(self, path: str): ...

    def use_manifest_filename(self, filename: str): ...

    def with_entrypoints(self, entries): ...

    def use_csp_nonce(self, nonce: str | None = None): ...

    def csp_nonce(self): ...

    def use_integrity_key(self, key: str | bool | None): ...

    def use_script_tag_attributes(self, attributes): ...

    def use_style_tag_attributes(self, attributes): ...

    def use_asset_prefetching(self, strategy: str = "load"): ...
