from __future__ import annotations

from typing import Protocol


class BladeFactoryContract(Protocol):
    def render(self, template: str, context: dict | None = None, request=None): ...

    def render_string(self, source: str, context: dict | None = None, request=None, origin: str | None = None): ...

    def directive(self, name: str, handler): ...

    def if_(self, name: str, handler): ...

    def stringable(self, value_type: type, handler): ...

    def without_double_encoding(self): ...
