from __future__ import annotations

from typing import Protocol


class SessionStoreContract(Protocol):
    def get(self, key: str, default=None): ...

    def all(self): ...

    def only(self, keys): ...

    def except_(self, keys): ...

    def put(self, key: str | dict, value=None): ...

    def push(self, key: str, value): ...

    def pull(self, key: str, default=None): ...

    def increment(self, key: str, amount: int = 1): ...

    def decrement(self, key: str, amount: int = 1): ...

    def has(self, key): ...

    def exists(self, key): ...

    def missing(self, key): ...

    def flash(self, key: str, value): ...

    def now(self, key: str, value): ...

    def reflash(self): ...

    def keep(self, keys): ...

    def forget(self, keys): ...

    def flush(self): ...

    def regenerate(self, destroy: bool = False): ...

    def invalidate(self): ...

    def token(self): ...

    def cache(self): ...
