from __future__ import annotations

from typing import Protocol


class UrlGeneratorContract(Protocol):
    def to(self, path: str = "/", extra: dict | None = None, secure: bool | None = None, absolute: bool = True): ...

    def query(self, path: str, query: dict): ...

    def current(self, request=None): ...

    def full(self, request=None): ...

    def previous(self, request=None, fallback="/"): ...

    def previous_path(self, request=None, fallback="/"): ...

    def route(self, name: str, parameters: dict | None = None, absolute: bool = True): ...

    def signed_route(self, name: str, parameters: dict | None = None, expiration=None, absolute: bool = True): ...

    def temporary_signed_route(self, name: str, expiration, parameters: dict | None = None, absolute: bool = True): ...

    def action(self, action, parameters: dict | None = None, absolute: bool = True): ...

    def defaults(self, defaults: dict): ...

    def has_valid_signature(self, request, absolute: bool = True, ignore=()): ...


class UriContract(Protocol):
    value: str

    def with_scheme(self, scheme: str): ...

    def with_host(self, host: str): ...

    def with_port(self, port: int | None): ...

    def with_path(self, path: str): ...

    def with_query(self, query: dict): ...

    def with_fragment(self, fragment: str): ...
