from __future__ import annotations

from typing import Protocol


class ValidatorContract(Protocol):
    def passes(self): ...

    def fails(self): ...

    def validate(self): ...

    def errors(self): ...

    def validated(self): ...

    def safe(self, keys=None): ...

    def after(self, callback): ...

    def sometimes(self, attribute, rules, condition): ...

    def stop_on_first_failure(self): ...


class ValidatorFactoryContract(Protocol):
    def make(self, data: dict, rules: dict, messages: dict | None = None, attributes: dict | None = None): ...

    def validate(self, data: dict, rules: dict, messages: dict | None = None, attributes: dict | None = None): ...

    def extend(self, rule: str, callback): ...
